### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Johnathen8** [cosmicnebula200/SellMe#10]
16.08 18:48:27 [Server] INFO [18:48:27.817] [Server thread/CRITICAL]: TypeError: "CortexPE\Commando\BaseSubCommand::__construct(): Argument #1 ($plugin) must be of type pocketmine\plugin\Plugin, string given, called in /plugins/SellMe-main/src/cosmicnebula200/SellMe/commands/SellCommand.php on line 32" (EXCEPTION) in "/virions/Commando_dev-3.phar/src/CortexPE/Commando/BaseSubCommand" at line 39
16.08 18:48:27 [Server] INFO --- Stack trace ---
16.08 18:48:27 [Server] INFO #0 plugins/SellMe-main/src/cosmicnebula200/SellMe/commands/SellCommand(32): CortexPE\Commando\BaseSubCommand->__construct(string[4] hand, string[40] Sells the item which is held by the user, array[1])
16.08 18:48:27 [Server] INFO #1 /virions/Commando_dev-3.phar/src/CortexPE/Commando/BaseCommand(88): cosmicnebula200\SellMe\commands\SellCommand->prepare()
16.08 18:48:27 [Server] INFO #2 plugins/SellMe-main/src/cosmicnebula200/SellMe/SellMe(69): CortexPE\Commando\BaseCommand->__construct(object cosmicnebula200\SellMe\SellMe#22503, string[4] sell, string[12] Sell command)
16.08 18:48:27 [Server] INFO #3 pmsrc/src/plugin/PluginBase(117): cosmicnebula200\SellMe\SellMe->onEnable()
16.08 18:48:27 [Server] INFO #4 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginBase->onEnableStateChange(true)
16.08 18:48:27 [Server] INFO #5 pmsrc/src/Server(1419): pocketmine\plugin\PluginManager->enablePlugin(object cosmicnebula200\SellMe\SellMe#22503)
16.08 18:48:27 [Server] INFO #6 pmsrc/src/Server(1024): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21897)
16.08 18:48:27 [Server] INFO #7 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[48] /, string[56] /plugins/)
16.08 18:48:27 [Server] INFO #8 pmsrc/src/PocketMine(327): pocketmine\server()
16.08 18:48:27 [Server] INFO #9 pmsrc(11): require(string[97] phar:///PMMP-Latest-Stable.phar/s)
16.08 18:48:27 [Server] INFO --- End of exception information ---
16.08 18:48:27 [Server] INFO [18:48:27.818] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by TacoError** [comment]
download from poggit, or add commando as a plugin virion using DEvirion https://poggit.pmmp.io/ci/CortexPE/Commando/Commando
https://poggit.pmmp.io/p/DEVirion/
