### ISSUE TITLE
Error: "Class "CortexPE\Commando\BaseCommand" not found"

### ISSUE THREAD

**Issue by ByLex-69bits** [cosmicnebula200/SellMe#9]
[Server thread/CRITICAL]: Error: "Class "CortexPE\Commando\BaseCommand" not found" (EXCEPTION) in "plugins/SellMe-main/src/cosmicnebula200/SellMe/commands/SellCommand" at line 19
--- Stack trace ---
  #0 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(93): include()
  #1 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(83): BaseClassLoader->loadClass(string[43] cosmicnebula200\SellMe\commands\SellCommand)
  #2 plugins/SellMe-main/src/cosmicnebula200/SellMe/SellMe(69): BaseClassLoader->{closure}(string[43] cosmicnebula200\SellMe\commands\SellCommand)
  #3 pmsrc/src/plugin/PluginBase(117): cosmicnebula200\SellMe\SellMe->onEnable()
  #4 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #5 pmsrc/src/Server(1419): pocketmine\plugin\PluginManager->enablePlugin(object cosmicnebula200\SellMe\SellMe#27228)
  #6 pmsrc/src/Server(1024): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#25756)
  #7 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #8 pmsrc/src/PocketMine(327): pocketmine\server()
  #9 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by ByLex-69bits** [comment]
ça arrive quand je lance le serv

**Comment by ByLex-69bits** [comment]
my bad j'avais juste pas le virion ça marche mtn

**Comment by cosmicnebula200** [comment]
get it from poggit bro
